name: "tests"

on: [push]

jobs:

  unit-tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 13.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run e2e-test
